apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: lingua-greeter-git-source
spec:
  type: git
  params: 
  - name: url
    value: https://github.com/kameshsampath/kn-lingua-greeter
  - name: revision
    value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name:  lingua-greeter-image
spec:
  type: image
  params: 
  - name: url
    # if you are minikube uncomment this line
    #value: "dev.local/rhdevelopers/stream-greeter"
    # if you are on OpenShift uncomment the line below
    value: "image-registry.openshift-image-registry.svc:5000/knativetutorial/lingua-greeter"